script: "./build-packages.sh"
git:
  depth: 10
branches:
  only:
  - master
os:
- linux
env:
  matrix:
  - ATOM_CHANNEL=stable
  global:
    secure: FJL1cYaW4O1oGU0OGzvQA0Zi47keCwylylbp3JKVO9p39Y7Ih224LB06oBKAsOcli1tGKx1e6JdSpYys/4mOkAA5AFpXtRDIyb+UP4XVdPbIfwhLzivHqpG75zxkTtFk435ylMd7jtjtBmfBMGooEutPTnurIFyM2C0FEzsDUmYFbqwrCAreKxA8Idbh6Nwa6oSGdY4dKockzyRMV/BorOWkKCXV0rc3jNCX5/Hb8Nu9YNngGDCgQnRIQjm0i9R1XE/mN3yJBXDVW2AQnXXyTH/KVFyjChNRk+llzwfXCPjJo7FiZqZLmx5pwtwoQPy3TdKgOgmerwoMDok4S0uIDGU0b+dHhW7b0IToBT3cbGtl9dKlQuAnYy/cTeaMlOaB+GbvR1yQsSp33byAJQaYpMkc1Csn/N9gzgmpr3lrDJ4h/VYF46T+quKxpNIPdYPZdhYtZ7jxEpPmwgEIGHFONP89jvr1OuUWGHyJcVqNGeDGf4ZX6DKBW0bShPte4O2MUK9GtonVZS8Bc/R78RRYSYls4HVxy4S6wC8ouUZKoFOBn5L5SWdmONNlQSw4UU4Jtl7u/T4Egta/sIGp2yKvVtN8XTcD7JJ7sAA8T+PohdUjhUYkUYyXMOLN0ZscHg502auVfCbRX1Ox3cfrxFtxKxK/6AAGyL446p9M66/7ZgA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - git
    - vim
