script: "./build-packages.sh"

git:
  depth: 10

branches:
  only:
  - master

os:
- linux

env:
  global:
  - secure: ih4D7hCxq6rHNZuZ/xNbVmOP2sc9Iox2CnBTB38JCGGf8UOQ3zrHHXTkrp2xsJ78keDN2wr7YVl3rDnhMUfc05N9cXJ2wTzIOe8ClR0BoxdAZpT1F56cEvtLiOXsy7horxs2OaG2ds8ydVBagr87LPkquXpaRomIRy+qvt2sb0p/YCqnKthw6K70pFUqyAU9glGz1y6FwNwd7JbeRw0xBch+rIWZ8C9ZgK/y8KAgACc1H/+W430tsgpCEBnBFoeB77ZYeYITtaX92fqRbdhi7/JFMwv5fEnRnFBDr81vgryroNHEh9gFqhcoK01td0tWkU+Uu2C0YLGVeldtgCv8gvEjcHE6G5QaOAb3v3we0nqCJTpmVGsfLo0DvLheKVqwCA1FJYqkvNbl+2XGYeLMmGkyYNhl44QgY2DzyVq9PWg3idwFMwLvZKVNpVMtyNUU0ABOVcR41AzYMiROe7sSah3cHmCUMGPBu85VwKBjVRF52WwYM1s3kLaEz6SE6634jIbU97HerIQP0unZZR//KFpIYvA1/Tpay1hMPfatHznrml8Af6kMSpBbzVS/rixOHlvlwibSNSc/FhOd4L55qrRi0HWcy7SdDERSXRG7Zk1/Hxi4ONzxVMlhPGMFP7uM7x7p/b/sv6GA4ziaqKxbGacS14kVycC31jwI0x7f3Qw=
  matrix:
  - ATOM_CHANNEL=stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - git
    - vim
